# Config format schema number
format_version: 4

###################
## Model options
model_params:
  grid_size:
    - 480
    - 360
    - 32

  fea_dim: 9
  ppmodel_init_dim: 32
  use_norm: True
  dropout: 0.5  # 0.2

  use_co_attention: True  # use co-attention gate


###################
## Data_loader options
data_loader:
calib_yaml: "/scratch/aadith_warrier/JRDB/calibration/lidars.yaml"  
pose_path:  "/scratch/aadith_warrier/JRDB/poses/"  
split_file: "config/jrdb_split.txt" 3. Launch training with  bash<br>python jrdb_trainer.py \ <br>  --arch_cfg config/MotionBEV-jrdb.yaml \<br>  --data_cfg config/jrdb_motion.yaml



###################
## Train params
train_params:
  name: "MotionBEV"
  model_load_path: "/scratch/gaurav_kumar/motionbev-project/MotionBEV/pretrain/MotionBEV-kitti-val-76.54.pt" # none for training from scratch
  checkpoint_every_n_steps: 500
  max_num_epochs: 100
  eval_every_n_steps: 1048  #1411 #1048
  learning_rate: 0.01
  optimizer: "SGD" # "SGD" "Adam" "AdamW"
  weight_decay: 0.0001   # weight decay
  momentum: 0.9          # sgd momentum
  wup_epochs: 1          # warmup during first XX epochs (can be float)
  lr_decay: 0.95         # learning rate decay per epoch after initial cycle (from min lr)
